#RabbitMQ
spring:
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        Data:
          group: rabbit-example
          consumer:
            maxAttempts: 1
            #count of connections to Rabbit
            concurrency: 2
            maxConcurrency: 5
            prefetch: 50
  rabbitmq:
    host: rabbit
    username: guest
    password: guest
    cache:
      channel:
        size: 200
management:
  health:
    binders:
      enabled: true